# Generated by Django 3.0.7 on 2020-06-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='erro',
            field=models.CharField(default='', max_length=200),
        ),
    ]
